#!/bin/bash
#  Copyright (C) 2000-2010, Parallels, Inc. All rights reserved.
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
# Adds IP address(es) in a container running Debian-like distro.

# Managed by Puppet

VENET_DEV=venet0
LOOPBACK=lo
CFGFILE=/etc/network/interfaces
HOSTFILE=/etc/hosts

function fix_networking_conf()
{
	local cfg="/etc/init/networking.conf"
	local str="local-filesystems"

	test -f ${cfg} || return 0
	fgrep -q "udevtrigger" ${cfg} 2>/dev/null || return 0

	fgrep -v "udevtrigger" ${cfg} | \
		sed "s,(${str},${str},g" > ${cfg}.$$ && \
		mv -f ${cfg}.$$ ${cfg}
}

function setup_network()
{
	echo "# This configuration file is auto-generated.
# WARNING: Do not edit this file, your changes will be lost.
# Please create/edit $CFGFILE.head and $CFGFILE.tail instead,
# their contents will be inserted at the beginning and at the end
# of this file, respectively.
#
# NOTE: it is NOT guaranteed that the contents of $CFGFILE.tail
# will be at the very end of this file.  
" > ${CFGFILE}

	if [ -f ${CFGFILE}.head ]; then
		cat ${CFGFILE}.head >> ${CFGFILE}
	fi

	if [ -f ${CFGFILE}.template ]; then
		cat ${CFGFILE}.template >> ${CFGFILE}
	fi
	# Set up loopback
	if ! grep -qw lo ${CFGFILE}; then
		echo "
# Auto generated ${LOOPBACK} interface
auto ${LOOPBACK}
iface ${LOOPBACK} inet loopback
" >> ${CFGFILE}
	fi

	# Set up /etc/hosts
	if [ ! -f $HOSTFILE ]; then
		echo "127.0.0.1 localhost.localdomain localhost" > $HOSTFILE

		if [ "${IPV6}" = "yes" ]; then
			echo "::1 localhost.localdomain localhost" >> $HOSTFILE
		fi
	fi

	if [ -n "${IP_ADDR}" ]; then
		# Set up venet0
		echo "
# Auto generated ${VENET_DEV} interface" >> ${CFGFILE}

	fi

	if [ -f ${CFGFILE}.tail ]; then
		cat ${CFGFILE}.tail >> ${CFGFILE}
	fi

	fix_networking_conf
}

function create_config()
{
	local ip=$1

	if [ "${ip#*:}" = "${ip}" ]; then
		if ! grep -q "iface ${VENET_DEV} inet static" ${CFGFILE}.ipv4 2>/dev/null ; then
			# Install the first IPv4 interface
			echo "iface ${VENET_DEV} inet static
	address ${ip}
	netmask 255.255.255.255
	broadcast 0.0.0.0
	up if [ -x /bin/ip ]; then ip route add default dev ${VENET_DEV}; exit 0; fi" >> ${CFGFILE}.ipv4
		else
			# Secondary IP, add it
			echo "	up if [ -x /bin/ip ]; then ip addr add ${ip} dev ${VENET_DEV}; exit 0; fi
	down if [ -x /bin/ip ]; then ip addr del ${ip} dev ${VENET_DEV}; exit 0; fi" >> ${CFGFILE}.ipv4
		fi
	else
		if ! grep -q "iface ${VENET_DEV} inet6 static" ${CFGFILE}.ipv6 2>/dev/null ; then
			# Install the firest IPv6 interface
			echo "iface ${VENET_DEV} inet6 static
	address ${ip}
	netmask 128
	up if [ -x /bin/ip ]; then ip -6 route add default dev ${VENET_DEV}; exit 0; fi" >> ${CFGFILE}.ipv6
		else
			# Secondary IP, add it
			echo "	up if [ -x /bin/ip ]; then ip -6 addr add ${ip} dev ${VENET_DEV}; exit 0; fi
	down if [ -x /bin/ip ]; then ip -6 addr del ${ip} dev ${VENET_DEV}; exit 0; fi" >> ${CFGFILE}.ipv6
		fi
	fi
}

function add_ip()
{
	local ip
	local add
	local iface

	setup_network

	if [ "${IPDELALL}" = "yes" ]; then
		ifdown ${VENET_DEV} >/dev/null 2>&1
		echo > ${CFGFILE}.ipv4
		echo > ${CFGFILE}.ipv6
	fi
	if [ -n "${IP_ADDR}" ]; then
		cp -f ${CFGFILE} ${CFGFILE}.bak
		for ip in ${IP_ADDR}; do
			if grep -w "${ip}" >/dev/null 2>&1 ${CFGFILE}.ipv4 ${CFGFILE}.ipv6; then
				continue
			fi
			create_config ${ip}
		done
		# Set venet dev to auto if it appears in the config
		if grep -q "iface ${VENET_DEV} inet" ${CFGFILE}.ipv4 ${CFGFILE}.ipv6 2>/dev/null ; then
			echo "auto ${VENET_DEV}" >> ${CFGFILE}.bak
		fi
		cat ${CFGFILE}.bak ${CFGFILE}.ipv4 ${CFGFILE}.ipv6 > ${CFGFILE}
	fi
	if [ "x${VE_STATE}" = "xrunning" ]; then
		ifdown --force ${VENET_DEV} 2> /dev/null
		ifup --force ${VENET_DEV} 2> /dev/null
	fi
}

add_ip

exit 0
